// Maps Spanish display_name values to country-flag-icons export names (underscored).
export const COUNTRY_FLAG_MAP: Record<string, string> = {
  "México": "MX",
  "Sudáfrica": "ZA",
  "Corea del Sur": "KR",
  "Chequia": "CZ",
  "Canadá": "CA",
  "Bosnia y Herzegovina": "BA",
  "Catar": "QA",
  "Suiza": "CH",
  "Brasil": "BR",
  "Marruecos": "MA",
  "Haití": "HT",
  "Escocia": "GB_SCT",
  "Estados Unidos": "US",
  "Paraguay": "PY",
  "Australia": "AU",
  "Turquía": "TR",
  "Alemania": "DE",
  "Curazao": "CW",
  "Costa de Marfil": "CI",
  "Ecuador": "EC",
  "Países Bajos": "NL",
  "Japón": "JP",
  "Suecia": "SE",
  "Túnez": "TN",
  "Bélgica": "BE",
  "Egipto": "EG",
  "Irán": "IR",
  "Nueva Zelanda": "NZ",
  "España": "ES",
  "Cabo Verde": "CV",
  "Arabia Saudí": "SA",
  "Uruguay": "UY",
  "Francia": "FR",
  "Senegal": "SN",
  "Irak": "IQ",
  "Noruega": "NO",
  "Argentina": "AR",
  "Argelia": "DZ",
  "Austria": "AT",
  "Jordania": "JO",
  "Portugal": "PT",
  "República Democrática del Congo": "CD",
  "Uzbekistán": "UZ",
  "Colombia": "CO",
  "Inglaterra": "GB_ENG",
  "Croacia": "HR",
  "Ghana": "GH",
  "Panamá": "PA",
};
