-- ═══════════════════════════════════════════════════════════════════════════
-- "La Porra Justa" (Fair Classification)
--
-- A fully PARALLEL, ADDITIVE pipeline. Nothing here touches match_results,
-- prediction_scores or the real scoring/leaderboard logic. The fair pipeline
-- treats the "Resultado Justo" (real 90' score minus regulation stoppage-time
-- goals) as if it were the real result and recomputes points with the SAME
-- scoring rules and the SAME pure scorer functions.
--
-- Three tables:
--   · fair_added_time_goals  — admin-entered source data (the only hand-edited
--                              fair table): goals scored from minute 90 onward
--                              that we subtract per team.
--   · fair_match_results     — derived "Resultado Justo" (regenerated wholesale
--                              by the fair recalc; never hand-edited).
--   · fair_prediction_scores — same shape as prediction_scores; regenerated by
--                              the fair recalc. Match rows recomputed from
--                              fair_match_results; initial / group_qualification
--                              rows copied verbatim from the real scores.
-- ═══════════════════════════════════════════════════════════════════════════


-- ─────────────────────────── fair_added_time_goals ──────────────────────────

create table public.fair_added_time_goals (
  id              uuid primary key default gen_random_uuid(),
  tournament_id   uuid not null references public.tournaments(id) on delete cascade,
  fixture_id      uuid not null references public.fixtures(id) on delete cascade,
  team_id         uuid not null references public.teams(id) on delete restrict,
  goals           integer not null check (goals > 0),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (fixture_id, team_id)
);

create index fair_added_time_goals_tournament_idx
  on public.fair_added_time_goals (tournament_id);
create index fair_added_time_goals_fixture_idx
  on public.fair_added_time_goals (fixture_id);

create trigger fair_added_time_goals_set_updated_at
  before update on public.fair_added_time_goals
  for each row execute function public.set_updated_at();


-- ─────────────────────────── fair_match_results ─────────────────────────────

-- Derived "Resultado Justo". Only fixtures with a CONFIRMED real match_results
-- row produce a fair row. Fully regenerated (delete + insert by tournament) on
-- each fair recalc.
create table public.fair_match_results (
  id                  uuid primary key default gen_random_uuid(),
  tournament_id       uuid not null references public.tournaments(id) on delete cascade,
  fixture_id          uuid not null unique references public.fixtures(id) on delete cascade,
  home_goals_90       integer not null check (home_goals_90 >= 0),
  away_goals_90       integer not null check (away_goals_90 >= 0),
  went_extra_time     boolean not null default false,
  went_penalties      boolean not null default false,
  winner_team_id      uuid references public.teams(id) on delete set null,
  qualified_team_id   uuid references public.teams(id) on delete set null,
  computed_at         timestamptz not null default now()
);

create index fair_match_results_tournament_idx
  on public.fair_match_results (tournament_id);


-- ─────────────────────────── fair_prediction_scores ─────────────────────────

-- Mirrors prediction_scores exactly. fixture_id is null for initial /
-- group_qualification rows. Regenerated wholesale by the fair recalc.
create table public.fair_prediction_scores (
  id                       uuid primary key default gen_random_uuid(),
  tournament_id            uuid not null references public.tournaments(id) on delete cascade,
  user_id                  uuid not null references public.profiles(user_id) on delete cascade,
  fixture_id               uuid references public.fixtures(id) on delete cascade,
  prediction_type          text not null
                             check (prediction_type in ('group_phase','knockout','initial','group_qualification')),
  scoring_rules_version    integer not null,
  points_total             numeric(8,2) not null,
  points_breakdown         jsonb not null,
  calculated_at            timestamptz not null default now()
);

create index fair_prediction_scores_user_idx     on public.fair_prediction_scores (tournament_id, user_id);
create index fair_prediction_scores_fixture_idx  on public.fair_prediction_scores (tournament_id, fixture_id);
create index fair_prediction_scores_type_idx     on public.fair_prediction_scores (tournament_id, prediction_type);


-- ─────────────────────────── RLS · all three tables ─────────────────────────

alter table public.fair_added_time_goals   enable row level security;
alter table public.fair_match_results       enable row level security;
alter table public.fair_prediction_scores  enable row level security;

-- Everyone authenticated may read the fair data (same posture as the real
-- prediction_scores / leaderboards).
create policy "fair_added_time_goals_select_authenticated"
  on public.fair_added_time_goals for select to authenticated using (true);

create policy "fair_match_results_select_authenticated"
  on public.fair_match_results for select to authenticated using (true);

create policy "fair_prediction_scores_select_authenticated"
  on public.fair_prediction_scores for select to authenticated using (true);

-- Only admins may write (the service-role recalc client bypasses RLS).
create policy "fair_added_time_goals_admin_all"
  on public.fair_added_time_goals for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "fair_match_results_admin_all"
  on public.fair_match_results for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "fair_prediction_scores_admin_all"
  on public.fair_prediction_scores for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
