-- ============================================================================
-- Migration: scoring — rules + per-prediction scores + leaderboard snapshots
-- ----------------------------------------------------------------------------
-- All three tables are derived/managed by the admin client only:
--  · scoring_rules versions are created/activated by the admin
--    (hito 14, scoring rules editor).
--  · prediction_scores are wiped and regenerated by the recalculation
--    engine (hito 11) every time a result is confirmed or a rule changes.
--  · leaderboard_snapshots are produced alongside scores and serve the
--    evolution chart in hito 12 without recomputing on every render.
-- Players read all three tables; only admins (or the service-role
-- client used by the recalculation engine) can write.
-- ============================================================================


-- ─────────────────────────── scoring_rules ──────────────────────────────────

-- Each row is one version of the rule set for a tournament. The "active"
-- version is the one consumed by the scoring engine. Old versions are kept
-- so scores carry the version they were computed with (auditable / replayable).
create table public.scoring_rules (
  id              uuid primary key default gen_random_uuid(),
  tournament_id   uuid not null references public.tournaments(id) on delete cascade,
  version         integer not null check (version > 0),
  rules           jsonb not null,
  active          boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (tournament_id, version)
);

create trigger scoring_rules_set_updated_at
  before update on public.scoring_rules
  for each row execute function public.set_updated_at();

-- At most one active rule set per tournament. Partial unique index.
create unique index scoring_rules_one_active_per_tournament
  on public.scoring_rules (tournament_id) where active;


-- ─────────────────────────── prediction_scores ──────────────────────────────

-- Derived: the recalculation engine deletes all rows for a tournament and
-- inserts the new ones from scratch. fixture_id is null for prediction_type
-- in {'initial','group_qualification'} which aren't tied to a single fixture.
create table public.prediction_scores (
  id                       uuid primary key default gen_random_uuid(),
  tournament_id            uuid not null references public.tournaments(id) on delete cascade,
  user_id                  uuid not null references public.profiles(user_id) on delete cascade,
  fixture_id               uuid references public.fixtures(id) on delete cascade,
  prediction_type          text not null
                             check (prediction_type in ('match','initial','group_qualification','knockout')),
  scoring_rules_version    integer not null,
  points_total             numeric(8,2) not null,
  points_breakdown         jsonb not null,
  calculated_at            timestamptz not null default now()
);

create index prediction_scores_user_idx     on public.prediction_scores (tournament_id, user_id);
create index prediction_scores_fixture_idx  on public.prediction_scores (tournament_id, fixture_id);
create index prediction_scores_type_idx     on public.prediction_scores (tournament_id, prediction_type);


-- ─────────────────────────── leaderboard_snapshots ──────────────────────────

-- Optional materialisation of the standings after each round. Rebuilt by
-- the same engine that fills prediction_scores (hito 12).
create table public.leaderboard_snapshots (
  id              uuid primary key default gen_random_uuid(),
  tournament_id   uuid not null references public.tournaments(id) on delete cascade,
  round_id        uuid not null references public.rounds(id) on delete cascade,
  user_id         uuid not null references public.profiles(user_id) on delete cascade,
  total_points    numeric(10,2) not null,
  rank            integer not null check (rank > 0),
  created_at      timestamptz not null default now(),
  unique (tournament_id, round_id, user_id)
);

create index leaderboard_snapshots_tournament_round_idx
  on public.leaderboard_snapshots (tournament_id, round_id, rank);


-- ─────────────────────────── RLS · all three tables ─────────────────────────

alter table public.scoring_rules          enable row level security;
alter table public.prediction_scores      enable row level security;
alter table public.leaderboard_snapshots  enable row level security;

create policy "scoring_rules_select_authenticated"
  on public.scoring_rules for select to authenticated using (true);

create policy "prediction_scores_select_authenticated"
  on public.prediction_scores for select to authenticated using (true);

create policy "leaderboard_snapshots_select_authenticated"
  on public.leaderboard_snapshots for select to authenticated using (true);

create policy "scoring_rules_admin_all"
  on public.scoring_rules for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "prediction_scores_admin_all"
  on public.prediction_scores for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "leaderboard_snapshots_admin_all"
  on public.leaderboard_snapshots for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
